### ISSUE TITLE
关于训练时的报错

### ISSUE THREAD

**Issue by TingZ-HIT** [Hymwgk/PointNetGPD#1]
请问一下博主几个训练网络时的报错问题：
1. main1v.py中的parser.add_argument('--data-path', type=str, default='~/dataset/PointNetGPD/', help='data path')需要修改吗，会显示dataset.py中self.transform = pickle.load(open(os.path.join(self.path, 'google2cloud.pkl'), 'rb'))在改路径下无法找到point2cloud.pkl文件
2. main1v.py函数中的shuffle需要改为False吗，不然也会报错
3. 在安装python-pcl的是时候会报一个cython的错误，博主是否有遇到过
3. 博主能否提供一下pytorch的版本，不清楚pytorch版本是否对本项目有影响

**Comment by Hymwgk** [comment]
> 请问一下博主几个训练网络时的报错问题：
> 
> 1. main1v.py中的parser.add_argument('--data-path', type=str, default='~/dataset/PointNetGPD/', help='data path')需要修改吗，会显示dataset.py中self.transform = pickle.load(open(os.path.join(self.path, 'google2cloud.pkl'), 'rb'))在改路径下无法找到point2cloud.pkl文件
> 2. main1v.py函数中的shuffle需要改为False吗，不然也会报错
> 3. 在安装python-pcl的是时候会报一个cython的错误，博主是否有遇到过
> 4. 博主能否提供一下pytorch的版本，不清楚pytorch版本是否对本项目有影响

1.要修改，根据自己的路径修改就行了，我刚又修改了一些路径错误，提交了一次
2.不用吧，我这里没有报错
3.然后python-pcl需要在虚拟环境中安装，安装前确保cython版本不要超过0.25.2 使用的版本是python-pcl-0.3.0rc1 ,确实比较难安装，遇到很多错误，但是没遇到过cpython的错误
4.conda3+pytorch1.7.1     conda2+pythorch1.4.0

**Comment by TingZ-HIT** [comment]
还想请问一下博主
1. 对于数据集的物体类别有要求吗? 因为数据集过大，我只生成了40个类别的点云图，我将对应的ycb_grasp和google_meshes数据也减少为40个，会对训练有影响吗？
2. 对于main.1v中的train函数最后返回值为float(correct)/float(dataset_size), 程序报错dataset_size为0，请问博主知道是什么原因吗？因为正常的话是dataset_size += data.shape[0]
3. 如果shuffle=True会报错ValuoError: num_samples should be a positive integer value,but got num_samples=0
4. 安装python-pcl时显示skipping 'pcl/_pcl_180.cpp' Cython extension(up-to-date), 但是在develop的时候似乎没有报错，显示Finished processing dependencies for python-pcl == 0.3.0rc1

**Comment by TingZ-HIT** [comment]
在训练时需要创建python2的虚拟环境吗

**Comment by Hymwgk** [comment]
> 还想请问一下博主
> 
> 1. 对于数据集的物体类别有要求吗? 因为数据集过大，我只生成了40个类别的点云图，我将对应的ycb_grasp和google_meshes数据也减少为40个，会对训练有影响吗？
> 2. 对于main.1v中的train函数最后返回值为float(correct)/float(dataset_size), 程序报错dataset_size为0，请问博主知道是什么原因吗？因为正常的话是dataset_size += data.shape[0]
> 3. 如果shuffle=True会报错ValuoError: num_samples should be a positive integer value,but got num_samples=0
> 4. 安装python-pcl时显示skipping 'pcl/_pcl_180.cpp' Cython extension(up-to-date), 但是在develop的时候似乎没有报错，显示Finished processing dependencies for python-pcl == 0.3.0rc1

1. 训练样本少了肯定是有影响的
2. 没遇到过这个，我机器上跑着没有报这个错的
3. shuffle就是打乱了样本，这样训练的时候会防止原始样本的分布对训练造成干扰；实在不行也可以关掉，只是可能训练效果没那么好罢了
4. python-pcl安装确实比较麻烦，很多种依赖的问题，可能还会遇到pcl动态连接库的问题，具体的步骤我没能记下来，安装上也就没再管他了，你可以试试新建一个虚拟环境再安装；情况多样，这点帮不了你了
5. “在训练时需要创建python2的虚拟环境吗？”训练是在conda3环境下的，建议仔细看下README，我在每个步骤后面分别标注了使用的是哪些环境

**Comment by TingZ-HIT** [comment]
在python3中的cython版本也需要<=0.25.2吗？

**Comment by TingZ-HIT** [comment]
我重新创建了虚拟环境为python3.5.6+pytorch1.1.0+cython0.25.2, 但是问题还是没有解决，还是存在skipping 'pcl/_pcl_180.cpp' Cython extension(up-to-date)的错误，但是运行main.py并没有报pcl的错误，不知道是否会影响训练代码。想和博主确认一下您电脑版本的配置以及路径是否还需要额外注意的地方。

**Comment by Hymwgk** [comment]
> 我重新创建了虚拟环境为python3.5.6+pytorch1.1.0+cython0.25.2, 但是问题还是没有解决，还是存在skipping 'pcl/_pcl_180.cpp' Cython extension(up-to-date)的错误，但是运行main.py并没有报pcl的错误，不知道是否会影响训练代码。想和博主确认一下您电脑版本的配置以及路径是否还需要额外注意的地方。

抱歉，我基本上就是按照原作者的要求实现的，我这里的修改也并不大，你要不多试试吧，试一下高版本的cython？原作者的要求是0.25.2，我的python3好像是大于这个版本的0.29吧好像

**Comment by Hymwgk** [comment]
长时间无回复

**Comment by xmkkkkkk** [comment]
> 还想请问一下博主
> 
> 1. 对于数据集的物体类别有要求吗? 因为数据集过大，我只生成了40个类别的点云图，我将对应的ycb_grasp和google_meshes数据也减少为40个，会对训练有影响吗？
> 2. 对于main.1v中的train函数最后返回值为float(correct)/float(dataset_size), 程序报错dataset_size为0，请问博主知道是什么原因吗？因为正常的话是dataset_size += data.shape[0]
> 3. 如果shuffle=True会报错ValuoError: num_samples should be a positive integer value,but got num_samples=0
> 4. 安装python-pcl时显示skipping 'pcl/_pcl_180.cpp' Cython extension(up-to-date), 但是在develop的时候似乎没有报错，显示Finished processing dependencies for python-pcl == 0.3.0rc1

你好，我遇到了几乎一摸一样的问题，你还记得2，3怎么解决的吗？
