### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by CaptainWuDaoKou** [Hymwgk/PointNetGPD#11]
博主你好，我看了原作者提供的数据集，每个点都是12维的数据，我只知道前3维是位置坐标，请问其他9维是什么信息？

**Comment by Hymwgk** [comment]
时间有点长,我差不多给忘记了; 不过, 印象中, 是(与[Dex-net](https://github.com/BerkeleyAutomation/dex-net)一致的)10维度的抓取配置 + 两个分数值(论文里有)

10维度的抓取配置参数,可以看[Dex-net](https://github.com/BerkeleyAutomation/dex-net)源码获取, 大概是 
[0:3] 夹爪中心坐标
[3:6] 夹爪Binomial轴单位向量
[6]  夹爪两指最大张开宽度
[7] 绕Binomial轴旋转角
[8] 抓取时夹爪两指目标闭合宽度
[9] 该型号夹爪两指最小闭合宽度

应该是这样, 可能记得有错, 有兴趣可以看看[Dex-net](https://github.com/BerkeleyAutomation/dex-net)里面我记得是grasp.py里面有定义, 但是具体含义需要结合代码理解,他们也没有具体解释(我没找到)

**Comment by CaptainWuDaoKou** [comment]
明白了，感谢
