### ISSUE TITLE
关于ubuntu20.04 中python-pcl的问题以及generate dataset canny

### ISSUE THREAD

**Issue by bigfacecat553** [Hymwgk/PointNetGPD#14]
1  由于python-pcl只支持pcl1.6-1.9，而ubuntu20.04配套的ros自带pcl1.10.   而dexnet中的部分功能似乎极大的依赖python-pcl。

2 后面关于generate dataset canny代码部分，我看过你的注释后，了解到：

 #如果每个摩擦系数下，有效的抓取(满足力闭合或者其他判断标准)小于要求值，就一直循环查找，直到所有摩擦系数条件下至少都存在20个有效抓取
    while np.sum(good_count_perfect < minimum_grasp_per_fc) != 0:    
        #开始使用antipodes sample获得对映随机抓取，此时并不判断是否满足力闭合，只是先采集满足夹爪条件的抓取
        #如果一轮多次随机采样之后，发现无法获得指定数量的随机抓取，就会重复迭代计算3次，之后放弃，并把已经找到的抓取返回来

我在参照步骤  python generate-dataset-canny.py [prefix]，然而终端中针对某一物体的采样 一直重复迭代3次， 之后似乎始终达不到全部要求，始终对一个物体进行计算。挂着跑了一天仍旧在对第一个物体002进行采样，generated_grasps文件夹始终为空。
我用了默认的 antipodal 采样方式。

**Comment by xiaofeiso** [comment]
你好，你解决问题了吗

**Comment by xiaofeiso** [comment]
我的结果跑出来，我尝试自己新建的obj，stl,ply文件，生成了default_google_512k_3000.npy和default_google_512k_3000.pickle。我开始也是这个问题，有一个可能是选择的模型的问题，我开始用solidworks画的，但单位是mm，而stl,obj是m。另外一个原因，可能是少了什么包，你可以看下https://blog.csdn.net/singlesmile/article/details/124946192?spm=1001.2014.3001.5506这个人的博客配置环境，应该没问题。

**Comment by bigfacecat553** [comment]
> ly文件，生成了default_google_512k_3000.npy和default_google_512k_3000.pickle。我开始也是这个问题，有一个可能是选择的模型的问题，我开始用solidwo

ubuntu 20.04 ros自带的pcl为1.10 不支持python-pcl 可以考虑删除pcl1.10 下载较低版本的pcl 或者 源码编译 pcl 再下pcl-python
又或者 直接 python3-pcl
另外一点 部分模型的采样始终不成功，达不到额定数量的抓取  可以考虑换一个模型
