### ISSUE TITLE
有关pointnetgpd训练的问题

### ISSUE THREAD

**Issue by xiaofeiso** [Hymwgk/PointNetGPD#15]
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])
你好，大佬我想问下原版的Pointnetgpd必须要训练完整的YCB数据集吗？不能只训练一部分吗？当我用python main_1v.py --epoch 200 --mode train --batch-size 16的时候，训练一轮后，就出现了KeyError: '037_scissors'，而我并没全部下载YCB数据集，只是想下载一部分训练。

**Comment by xiaofeiso** [comment]
这是我的输出：
/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:143: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Train Epoch: 0 [0/13000 (0.0%)]	Loss: 0.7988783121109009	default
Train Epoch: 0 [160/13000 (1.2307692307692308%)]	Loss: 0.9982127547264099default
Train Epoch: 0 [320/13000 (2.4615384615384617%)]	Loss: 0.4808115065097809default
Train Epoch: 0 [480/13000 (3.6923076923076925%)]	Loss: 0.8187177777290344default
Train Epoch: 0 [640/13000 (4.923076923076923%)]	Loss: 0.6008525490760803	default
Train Epoch: 0 [800/13000 (6.153846153846154%)]	Loss: 0.5981813669204712	default
Train Epoch: 0 [960/13000 (7.384615384615385%)]	Loss: 0.5543386936187744	default
Train Epoch: 0 [1120/13000 (8.615384615384615%)]	Loss: 0.739797830581665default
Train Epoch: 0 [1280/13000 (9.846153846153847%)]	Loss: 0.46812891960144043	default
Train Epoch: 0 [1440/13000 (11.076923076923077%)]	Loss: 0.6056610941886902default
Train Epoch: 0 [1600/13000 (12.307692307692308%)]	Loss: 0.8759855628013611default
Train Epoch: 0 [1760/13000 (13.538461538461538%)]	Loss: 0.494386225938797default
Train Epoch: 0 [1920/13000 (14.76923076923077%)]	Loss: 0.6670324206352234default
Train Epoch: 0 [2080/13000 (16.0%)]	Loss: 0.5689802765846252	default
Train Epoch: 0 [2240/13000 (17.23076923076923%)]	Loss: 0.7845731973648071default
Train Epoch: 0 [2400/13000 (18.46153846153846%)]	Loss: 0.5306569337844849default
Train Epoch: 0 [2560/13000 (19.692307692307693%)]	Loss: 0.8269679546356201default
Train Epoch: 0 [2720/13000 (20.923076923076923%)]	Loss: 0.9380084276199341default
Train Epoch: 0 [2880/13000 (22.153846153846153%)]	Loss: 0.7132447957992554default
Train Epoch: 0 [3040/13000 (23.384615384615383%)]	Loss: 0.523125946521759default
Train Epoch: 0 [3200/13000 (24.615384615384617%)]	Loss: 0.7239018678665161default
Train Epoch: 0 [3360/13000 (25.846153846153847%)]	Loss: 0.61322420835495	default
Train Epoch: 0 [3520/13000 (27.076923076923077%)]	Loss: 0.7838871479034424default
Train Epoch: 0 [3680/13000 (28.307692307692307%)]	Loss: 0.5374870896339417default
Train Epoch: 0 [3840/13000 (29.53846153846154%)]	Loss: 0.6299829483032227default
Train Epoch: 0 [4000/13000 (30.76923076923077%)]	Loss: 0.7041290402412415default
Train Epoch: 0 [4160/13000 (32.0%)]	Loss: 0.6583899855613708	default
Train Epoch: 0 [4320/13000 (33.23076923076923%)]	Loss: 0.7360888123512268default
Train Epoch: 0 [4480/13000 (34.46153846153846%)]	Loss: 0.5255335569381714default
Train Epoch: 0 [4640/13000 (35.69230769230769%)]	Loss: 0.5621503591537476default
Train Epoch: 0 [4800/13000 (36.92307692307692%)]	Loss: 0.6421205401420593default
Train Epoch: 0 [4960/13000 (38.15384615384615%)]	Loss: 0.7579902410507202default
Train Epoch: 0 [5120/13000 (39.38461538461539%)]	Loss: 0.7263869047164917default
Train Epoch: 0 [5280/13000 (40.61538461538461%)]	Loss: 0.6774408221244812default
Train Epoch: 0 [5440/13000 (41.84615384615385%)]	Loss: 0.4212123155593872default
Train Epoch: 0 [5600/13000 (43.07692307692308%)]	Loss: 0.48691922426223755	default
Train Epoch: 0 [5760/13000 (44.30769230769231%)]	Loss: 0.5608365535736084default
Train Epoch: 0 [5920/13000 (45.53846153846154%)]	Loss: 0.6132243871688843default
Train Epoch: 0 [6080/13000 (46.76923076923077%)]	Loss: 0.5581293702125549default
Train Epoch: 0 [6240/13000 (48.0%)]	Loss: 0.3667472004890442	default
Train Epoch: 0 [6400/13000 (49.23076923076923%)]	Loss: 0.43678411841392517	default
Train Epoch: 0 [6560/13000 (50.46153846153846%)]	Loss: 0.4772752821445465default
Train Epoch: 0 [6720/13000 (51.69230769230769%)]	Loss: 0.3846606910228729default
Train Epoch: 0 [6880/13000 (52.92307692307692%)]	Loss: 0.6068456172943115default
Train Epoch: 0 [7040/13000 (54.15384615384615%)]	Loss: 0.6226972937583923default
Train Epoch: 0 [7200/13000 (55.38461538461539%)]	Loss: 0.7099041938781738default
Train Epoch: 0 [7360/13000 (56.61538461538461%)]	Loss: 0.4035223722457886default
Train Epoch: 0 [7520/13000 (57.84615384615385%)]	Loss: 0.857866644859314default
Train Epoch: 0 [7680/13000 (59.07692307692308%)]	Loss: 0.8801365494728088default
Train Epoch: 0 [7840/13000 (60.30769230769231%)]	Loss: 0.38325515389442444	default
Train Epoch: 0 [8000/13000 (61.53846153846154%)]	Loss: 0.38329944014549255	default
Train Epoch: 0 [8160/13000 (62.76923076923077%)]	Loss: 0.46159079670906067	default
Train Epoch: 0 [8320/13000 (64.0%)]	Loss: 0.5591381192207336	default
Train Epoch: 0 [8480/13000 (65.23076923076923%)]	Loss: 0.6799395680427551default
Train Epoch: 0 [8640/13000 (66.46153846153847%)]	Loss: 0.6988914012908936default
Train Epoch: 0 [8800/13000 (67.6923076923077%)]	Loss: 0.4937935769557953	default
Train Epoch: 0 [8960/13000 (68.92307692307692%)]	Loss: 0.9422487020492554default
Train Epoch: 0 [9120/13000 (70.15384615384616%)]	Loss: 0.4705508053302765default
Train Epoch: 0 [9280/13000 (71.38461538461539%)]	Loss: 0.5365563035011292default
Train Epoch: 0 [9440/13000 (72.61538461538461%)]	Loss: 0.498940110206604	default
Train Epoch: 0 [9600/13000 (73.84615384615384%)]	Loss: 0.40524908900260925default
Train Epoch: 0 [9760/13000 (75.07692307692308%)]	Loss: 0.5813103318214417default
Train Epoch: 0 [9920/13000 (76.3076923076923%)]	Loss: 0.4172394871711731	default
Train Epoch: 0 [10080/13000 (77.53846153846153%)]	Loss: 0.36614876985549927default
Train Epoch: 0 [10240/13000 (78.76923076923077%)]	Loss: 0.29587888717651367default
Train Epoch: 0 [10400/13000 (80.0%)]	Loss: 0.6818849444389343	default
Train Epoch: 0 [10560/13000 (81.23076923076923%)]	Loss: 0.4547698497772217default
Train Epoch: 0 [10720/13000 (82.46153846153847%)]	Loss: 0.5056614875793457default
Train Epoch: 0 [10880/13000 (83.6923076923077%)]	Loss: 0.37007105350494385default
Train Epoch: 0 [11040/13000 (84.92307692307692%)]	Loss: 1.1905308961868286default
Train Epoch: 0 [11200/13000 (86.15384615384616%)]	Loss: 1.138736605644226	default
Train Epoch: 0 [11360/13000 (87.38461538461539%)]	Loss: 0.33943110704421997default
Train Epoch: 0 [11520/13000 (88.61538461538461%)]	Loss: 0.636604368686676	default
Train Epoch: 0 [11680/13000 (89.84615384615384%)]	Loss: 0.5057242512702942default
Train Epoch: 0 [11840/13000 (91.07692307692308%)]	Loss: 0.536013662815094	default
Train Epoch: 0 [12000/13000 (92.3076923076923%)]	Loss: 0.4108208417892456default
Train Epoch: 0 [12160/13000 (93.53846153846153%)]	Loss: 0.4399988353252411default
Train Epoch: 0 [12320/13000 (94.76923076923077%)]	Loss: 0.41554099321365356default
Train Epoch: 0 [12480/13000 (96.0%)]	Loss: 0.4782956540584564	default
Train Epoch: 0 [12640/13000 (97.23076923076923%)]	Loss: 0.3549630641937256default
Train Epoch: 0 [12800/13000 (98.46153846153847%)]	Loss: 0.4164580702781677default
Train Epoch: 0 [12960/13000 (99.6923076923077%)]	Loss: 0.5983869433403015default
Train done, acc=0.6896335734419041
Traceback (most recent call last):
  File "main_1v.py", line 192, in <module>
    main()
  File "main_1v.py", line 176, in main
    acc, loss = test(model, test_loader)
  File "main_1v.py", line 97, in test
    for data, target, obj_name in loader:
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/f/code/PointNetGPD/PointNetGPD/model/dataset.py", line 789, in __getitem__
    fl_pc = np.array(self.d_pc[obj_pc])
KeyError: '037_scissors'

**Comment by xmkkkkkk** [comment]
> ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512]) 你好，大佬我想问下原版的Pointnetgpd必须要训练完整的YCB数据集吗？不能只训练一部分吗？当我用python main_1v.py --epoch 200 --mode train --batch-size 16的时候，训练一轮后，就出现了KeyError: '037_scissors'，而我并没全部下载YCB数据集，只是想下载一部分训练。

你好，我也遇到了这个问题，请问你最后解决了嘛？
