### ISSUE TITLE
大佬！强烈希望能够在B站看到您复现过程的视频！球球了

### ISSUE THREAD

**Issue by chenyunbo-cyb** [Hymwgk/PointNetGPD#7]
大佬！强烈希望能够在B站看到您复现过程的视频！球球了

**Comment by Hymwgk** [comment]
谢谢，我只是一只菜鸟。目前没有再接着pointnetgpd思路做，不过近期会把候选检测阶段的代码从python替换为基于[atenpas/gpg]项目的C++代码，python检测速度太慢；如果还有兴趣可以关注 https://github.com/Hymwgk/gpg
